/* Country dialing codes for the phone-number input.
   Shown as "flag code" in the select, submitted as a prefix on the number.
   Sorted: US/Canada first, then alphabetically by country name. */

export interface CountryCode {
	code: string;     // e.g. "+1"
	country: string;  // e.g. "United States / Canada"
	flag: string;     // emoji flag
}

export const COUNTRY_CODES: CountryCode[] = [
	{ code: "+1",   country: "United States / Canada", flag: "🇺🇸" },
	{ code: "+54",  country: "Argentina",              flag: "🇦🇷" },
	{ code: "+61",  country: "Australia",              flag: "🇦🇺" },
	{ code: "+43",  country: "Austria",                flag: "🇦🇹" },
	{ code: "+880", country: "Bangladesh",             flag: "🇧🇩" },
	{ code: "+32",  country: "Belgium",                flag: "🇧🇪" },
	{ code: "+591", country: "Bolivia",                flag: "🇧🇴" },
	{ code: "+55",  country: "Brazil",                 flag: "🇧🇷" },
	{ code: "+56",  country: "Chile",                  flag: "🇨🇱" },
	{ code: "+86",  country: "China",                  flag: "🇨🇳" },
	{ code: "+57",  country: "Colombia",               flag: "🇨🇴" },
	{ code: "+506", country: "Costa Rica",             flag: "🇨🇷" },
	{ code: "+420", country: "Czech Republic",         flag: "🇨🇿" },
	{ code: "+45",  country: "Denmark",                flag: "🇩🇰" },
	{ code: "+1809",country: "Dominican Republic",     flag: "🇩🇴" },
	{ code: "+593", country: "Ecuador",                flag: "🇪🇨" },
	{ code: "+20",  country: "Egypt",                  flag: "🇪🇬" },
	{ code: "+503", country: "El Salvador",            flag: "🇸🇻" },
	{ code: "+358", country: "Finland",                flag: "🇫🇮" },
	{ code: "+33",  country: "France",                 flag: "🇫🇷" },
	{ code: "+49",  country: "Germany",                flag: "🇩🇪" },
	{ code: "+30",  country: "Greece",                 flag: "🇬🇷" },
	{ code: "+502", country: "Guatemala",              flag: "🇬🇹" },
	{ code: "+504", country: "Honduras",               flag: "🇭🇳" },
	{ code: "+36",  country: "Hungary",                flag: "🇭🇺" },
	{ code: "+91",  country: "India",                  flag: "🇮🇳" },
	{ code: "+62",  country: "Indonesia",              flag: "🇮🇩" },
	{ code: "+353", country: "Ireland",                flag: "🇮🇪" },
	{ code: "+972", country: "Israel",                 flag: "🇮🇱" },
	{ code: "+39",  country: "Italy",                  flag: "🇮🇹" },
	{ code: "+81",  country: "Japan",                  flag: "🇯🇵" },
	{ code: "+254", country: "Kenya",                  flag: "🇰🇪" },
	{ code: "+82",  country: "South Korea",            flag: "🇰🇷" },
	{ code: "+60",  country: "Malaysia",               flag: "🇲🇾" },
	{ code: "+52",  country: "Mexico",                 flag: "🇲🇽" },
	{ code: "+212", country: "Morocco",                flag: "🇲🇦" },
	{ code: "+31",  country: "Netherlands",            flag: "🇳🇱" },
	{ code: "+64",  country: "New Zealand",            flag: "🇳🇿" },
	{ code: "+505", country: "Nicaragua",              flag: "🇳🇮" },
	{ code: "+234", country: "Nigeria",                flag: "🇳🇬" },
	{ code: "+47",  country: "Norway",                 flag: "🇳🇴" },
	{ code: "+92",  country: "Pakistan",               flag: "🇵🇰" },
	{ code: "+507", country: "Panama",                 flag: "🇵🇦" },
	{ code: "+595", country: "Paraguay",               flag: "🇵🇾" },
	{ code: "+51",  country: "Peru",                   flag: "🇵🇪" },
	{ code: "+63",  country: "Philippines",            flag: "🇵🇭" },
	{ code: "+48",  country: "Poland",                 flag: "🇵🇱" },
	{ code: "+351", country: "Portugal",               flag: "🇵🇹" },
	{ code: "+1787",country: "Puerto Rico",            flag: "🇵🇷" },
	{ code: "+40",  country: "Romania",                flag: "🇷🇴" },
	{ code: "+7",   country: "Russia",                 flag: "🇷🇺" },
	{ code: "+966", country: "Saudi Arabia",           flag: "🇸🇦" },
	{ code: "+65",  country: "Singapore",              flag: "🇸🇬" },
	{ code: "+27",  country: "South Africa",           flag: "🇿🇦" },
	{ code: "+34",  country: "Spain",                  flag: "🇪🇸" },
	{ code: "+46",  country: "Sweden",                 flag: "🇸🇪" },
	{ code: "+41",  country: "Switzerland",            flag: "🇨🇭" },
	{ code: "+66",  country: "Thailand",               flag: "🇹🇭" },
	{ code: "+90",  country: "Turkey",                 flag: "🇹🇷" },
	{ code: "+380", country: "Ukraine",                flag: "🇺🇦" },
	{ code: "+971", country: "UAE",                    flag: "🇦🇪" },
	{ code: "+44",  country: "United Kingdom",         flag: "🇬🇧" },
	{ code: "+598", country: "Uruguay",                flag: "🇺🇾" },
	{ code: "+58",  country: "Venezuela",              flag: "🇻🇪" },
	{ code: "+84",  country: "Vietnam",                flag: "🇻🇳" },
];
